# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.7.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow qrcode
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install ttf
        run: |
          sudo apt install ttf-mscorefonts-installer
          sudo fc-cache
          sudo fc-match Arial
        
      - name: Run python code
        run: |
          python qrcode_gen.py

